controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    drive_controller:
      type: forward_command_controller/ForwardCommandController
    steer_controller:
      type: forward_command_controller/ForwardCommandController
joint_state_broadcaster:
  ros__parameters:
    joints: [drive_joint, steer_joint]
    interfaces: [position, velocity]
drive_controller:
  ros__parameters:
    joints: [drive_joint]
    interface_name: velocity
steer_controller:
  ros__parameters:
    joints: [steer_joint]
    interface_name: position
